# -*- coding: utf-8 -*-
"""internship_Neural_Style_Transfer .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GKDcKsUpZHLfRVTwC46KhrrXQISmVVXn
"""

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing.image import load_img, img_to_array

from google.colab import files
uploaded = files.upload()

import tensorflow as tf
import tensorflow_hub as hub
import numpy as np
import matplotlib.pyplot as plt

from tensorflow.keras.preprocessing.image import load_img, img_to_array

def load_image(path):
    img = load_img(path, target_size=(256, 256))
    img = img_to_array(img)
    img = img / 255.0
    img = np.expand_dims(img, axis=0)
    return tf.constant(img, dtype=tf.float32)

content_image = load_image("content.jpg")
style_image = load_image("style.jpg")

plt.imshow(np.squeeze(content_image))
plt.title("Content Image")
plt.axis("off")
plt.show()

plt.imshow(np.squeeze(style_image))
plt.title("Style Image")
plt.axis("off")
plt.show()

!pip install tensorflow_hub

model = hub.load(
    'https://tfhub.dev/google/magenta/arbitrary-image-stylization-v1-256/2'
)

stylized_image = model(content_image, style_image)[0]

plt.figure(figsize=(10,10))
plt.imshow(np.squeeze(stylized_image))
plt.title("Stylized Output")
plt.axis("off")
plt.show()

import matplotlib.image as mpimg

mpimg.imsave("output.jpg", np.squeeze(stylized_image))

from google.colab import files
files.download("output.jpg")

